# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  EasyInsuranceAPI:
    image: EasyInsuranceAPI
    build:
      context: .
      dockerfile: EasyInsuranceAPI/Dockerfile
      target: development
    ports:
      - 3000:3000
      - 3001:3001
    environment:
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
